language: ruby

bundler_args: --without debugger

script: bundle exec rake spec

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
notifications:
  email:
    recipients:
      - ngiger@ywesee.com
      - yasaka@ywesee.com
      - zdavatz@ywesee.com
